server:
  port: 12990

# mysql
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/configuration_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: configurationAdmin
    password: ySZCSsQT!TX4
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 5
      minimum-idle: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
        ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true
   ## 静态资源映射
  resources:
    static-locations: classpath:/static/,classpath:/views/

  mvc:
    view:
      suffix: .html
    static-path-pattern: /**


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml

jwt:
  # 加密秘钥
  secret: f4e2e52034348f86b67cde581c0f9eb5
  # token有效时长，7天，单位秒
  expire: 604800
  header: token

